# permissions for end users to view https.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: http-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: http
    app.kubernetes.io/part-of: http
    app.kubernetes.io/managed-by: kustomize
  name: http-viewer-role
rules:
- apiGroups:
  - api.gokula.zinkworks
  resources:
  - https
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.gokula.zinkworks
  resources:
  - https/status
  verbs:
  - get
